%define INSTANCEHOME /home/skynet/my_project/plone.all_in_one_accessibility/parts/instance
instancehome $INSTANCEHOME
%define CLIENTHOME /home/skynet/my_project/plone.all_in_one_accessibility/var/instance
clienthome $CLIENTHOME
debug-mode off
security-policy-implementation C
verbose-security off
default-zpublisher-encoding utf-8
<environment>
    zope_i18n_compile_mo_files true
CHAMELEON_CACHE /home/skynet/my_project/plone.all_in_one_accessibility/var/cache
</environment>
<zodb_db main>
    # Main database
    cache-size 30000
    # Blob-enabled FileStorage database
    <blobstorage>
      blob-dir /home/skynet/my_project/plone.all_in_one_accessibility/var/blobstorage
      # FileStorage database
      <filestorage>
        path /home/skynet/my_project/plone.all_in_one_accessibility/var/filestorage/Data.fs
      </filestorage>
    </blobstorage>
    mount-point /
</zodb_db>
python-check-interval 1000